[project]
name = "ai-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adem Usta", email = "mr.usta.adem@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.9.9",
]

[project.scripts]
ai-agents = "ai_agents:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
